[package]
name = "rusty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rusty_vault"
crate-type = ["rlib", "cdylib"]

[dependencies]
libc = "0.2.85"